#!/bin/sh

set -e

mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rmdir .git/tags_lock" EXIT

PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --languages=-sql,-css --exclude=.git --exclude=node_modules --exclude='*\.min\.*' # --languages=-javascript,sql
mv .git/tags.$$ .git/tags
