Rails:
  Enabled: true

EmptyLines:
  Enabled: false

# parens in method defs are needless noise
Style/MethodDefParentheses:
  Enabled: false

# this visually differentiates named arguments from assignment
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# use raise or Kernel.abort.  no need to ever use fail
Style/SignalException:
  EnforcedStyle: only_raise

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

# assignments in conditionals are always surprising.
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false
Lint/AssignmentInCondition:
  AllowSafeAssignment: false
