# Rails:
#   Enabled: true

# sometimes 2 blank lines offer a nice separation of subjects
# EmptyLines:
#   Enabled: false

# parens in method defs are needless noise
Style/MethodDefParentheses:
  Enabled: false

# this visually differentiates named arguments from assignment
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# use raise or Kernel.abort.  no need to ever use fail
Style/SignalException:
  EnforcedStyle: only_raise

# %w[] makes it clear it's an array.  https://github.com/bbatsov/ruby-style-guide/pull/563
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': []
    '%I': []
    '%w': []
    '%W': []

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

# assignments in conditionals are always surprising.
Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false
Lint/AssignmentInCondition:
  AllowSafeAssignment: false

# multi-line stabby procs are A-OK.  https://github.com/bbatsov/rubocop/issues/1520
Style/Lambda:
  Enabled: false

# no I'm not going to stick this comment in every single source file
Style/FrozenStringLiteralComment:
  Enabled: false

# for small arrays I definitely prefer [:a] to %i[a]
Style/SymbolArray:
  Enabled: false

# I often want two-line empty methods: easier to edit and often looks less cluttered
Style/EmptyMethod:
  Enabled: false
