# Default bash settings

#
# Environment
#

export LESS="--RAW-CONTROL-CHARS"    # interpret any embedded ansi escapes
export PAGER='less'                  # use less to view manpages, etc
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)" # let less show non-text files too
export PS1="\\u@\h \\w\\$ "          # simple prompt shows user, host and path

[ -f /etc/bash_completion ] && source /etc/bash_completion
[ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"

# Disable annoying ~ expansion
# http://www.linuxquestions.org/questions/linux-software-2/how-to-stop-bash-from-replacing-%7E-with-home-username-643162/#post3162026
_expand() { return 0; }
__expand_tilde_by_ref() { return 0; }


#
# Colors
#

if [ -x /usr/bin/dircolors ]; then
    # use ~/.dircolors if user has specified one
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi

export GREP_OPTIONS='--color=auto'


#
# History
#

shopt -s histappend                         # Append to history file instead of overwriting
shopt -s cmdhist                            # store multiline commands as 1 line
shopt -s cdspell                            # spelling error correction
shopt -s checkwinsize                       # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.
export HISTCONTROL="ignoreboth"             # store duplicate lines once, ignore lines beginning with a space
export HISTIGNORE="&:ls:[bf]g:exit:%[0-9]"  # ignore simple commands
export HISTFILESIZE=5000                    # history file size

# this doesn't seem to work, might have to switch to zsh
# export PROMPT_COMMAND="history -n; history -a" # store & reload history every time prompt is displayed, http://briancarper.net/blog/248/


#
# Aliases
#

alias ..='cd ..'
alias ...='cd ../..'
alias md='mkdir -p'
alias mdcd='f () { mkdir -p $1 && cd $1; }; f'

alias l='ls -CF'
alias la='ls -A'
alias ll='ls -lF'
alias lla='ls -alF'

alias tf='tail -f'

alias ga='git add'
alias gb='git b'
alias gc='git commit'
alias gd='git diff'
alias gl='git log'
alias gs='git s'

